spring.application.name=bankdemo

server.port=8080

account.default-amount=500
account.transfer-commission=5

spring.datasource.url=jdbc:postgresql://localhost:5432/bankdemo
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
